baseurl = "https://homelabrafael.com"
languageCode = "en-us"
theme = "terminal"
paginate = 5
enableGitInfo = true

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 2
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true
  autoCover = true
  showLastUpdated = true
  updatedDatePrefix = "Updated"
  Toc = true
  TocTitle = "echo \"Table of Contents\""
  favicon = "favicon.svg"

[languages]
  [languages.en]
    languageName = "English"
    title = "echo \"Rafael Moreira's Personal Website\""
    description = "Just an engineer's personal website, with thoughts, tutorials and rants about stuff engineers do."
    owner = "Rafael Moreira"
    keywords = "DevOps, Docker, Kubernetes, SysOps, Linux"
    menuMore = "echo \"Show more\""
    readMore = "echo \"Read More\""
    readOtherPosts = "echo \"Read other posts\""
    newerPosts = "echo \"Newer posts\""
    olderPosts = "echo \"Older posts\""
    missingContentMessage = "echo \"Page not found...\""
    missingBackButtonLabel = "echo \"Back to home page\""

    [languages.en.params.logo]
      logoText = "echo \"Homepage\""
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "echo \"About Me\""
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "contact"
        name = "echo \"Contact Me\""
        url = "/contact"