baseurl = "https://homelabrafael.com/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 2
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true
  autoCover = true
  showLastUpdated = false
  updatedDatePrefix = "Updated"
  Toc = true
  TocTitle = "echo \"Table of Contents\""

[languages]
  [languages.en]
    languageName = "English"
    title = "echo \"Rafael Moreira\""
    subtitle = "A simple, retro theme for Hugo"
    owner = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "echo \"Rafael Moreira\""
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "echo \"About Me\""
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "contact"
        name = "echo \"Contact Me\""
        url = "/contact"